configurable header description and hint for bounty programs
MetricsDAO/bounty_app pull request #14
Opened 2022-09-12 21:43 UTC by thehannahlerman

2022-09-12 21:50 UTC, thehannahlerman commented
This is how you can now make a bounty program custom. 
![Screen Shot 2022-09-12 at 5 50 31 PM](https://user-images.githubusercontent.com/43100701/189764949-3bbfddfa-3a99-4ac9-b0b1-039f474d982b.png)

2022-09-13 01:43 UTC, thekakamora requested changes

2022-09-13 01:43 UTC, thekakamora commented on frontend/pages/bounty-programs/[bountyProgramSlug]/index.tsx
> +            {bountyProgram.customDescription}
Can you please check if we can insert <br> in the `bountyProgram.customDescription` ? As you see in the text above if we have to configure through JSON then we need ability to add line breaks one way or other.

2022-09-13 01:43 UTC, thekakamora commented on frontend/pages/bounty-programs/[bountyProgramSlug]/index.tsx
> +                mixpanel.track("click:bounty_question_tips");
Looks like we did not allow configuring the onclick url - `click:bounty_question_tips`. Please allow configuring the URL along with the text. 

Also can you please provide ability not to have this link? For example we may have another field in json that says `disableHint: true` or something similar

2022-09-13 14:38 UTC, thehannahlerman commented
@thekakamora  So in the changes I push up, you will be able to just use "\n\n" to create a new line in the string wherever you want. Also as you can see on the /bounty-programs/goldfinch route in the preview branch, you can just insert emojis in the description string and they should work fine. I have also added the ability to make a custom hint link and disable the hint altogether. Let me know how this works for you and if there is anything else

2022-09-15 20:53 UTC, merged